// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: v2/hello_v2.proto

package hellov2pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Hellov2_SayHello_FullMethodName = "/hellov2pb.hellov2/SayHello"
)

// Hellov2Client is the client API for Hellov2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Hellov2Client interface {
	SayHello(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SayHelloResponse, error)
}

type hellov2Client struct {
	cc grpc.ClientConnInterface
}

func NewHellov2Client(cc grpc.ClientConnInterface) Hellov2Client {
	return &hellov2Client{cc}
}

func (c *hellov2Client) SayHello(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SayHelloResponse, error) {
	out := new(SayHelloResponse)
	err := c.cc.Invoke(ctx, Hellov2_SayHello_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Hellov2Server is the server API for Hellov2 service.
// All implementations must embed UnimplementedHellov2Server
// for forward compatibility
type Hellov2Server interface {
	SayHello(context.Context, *Empty) (*SayHelloResponse, error)
	mustEmbedUnimplementedHellov2Server()
}

// UnimplementedHellov2Server must be embedded to have forward compatible implementations.
type UnimplementedHellov2Server struct {
}

func (UnimplementedHellov2Server) SayHello(context.Context, *Empty) (*SayHelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedHellov2Server) mustEmbedUnimplementedHellov2Server() {}

// UnsafeHellov2Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Hellov2Server will
// result in compilation errors.
type UnsafeHellov2Server interface {
	mustEmbedUnimplementedHellov2Server()
}

func RegisterHellov2Server(s grpc.ServiceRegistrar, srv Hellov2Server) {
	s.RegisterService(&Hellov2_ServiceDesc, srv)
}

func _Hellov2_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Hellov2Server).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hellov2_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Hellov2Server).SayHello(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Hellov2_ServiceDesc is the grpc.ServiceDesc for Hellov2 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Hellov2_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hellov2pb.hellov2",
	HandlerType: (*Hellov2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Hellov2_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v2/hello_v2.proto",
}
