// Code generated by jzero. DO NOT EDIT.

package zrpcclient_go

import (
	"github.com/zeromicro/go-zero/zrpc"

	"simplerpc/zrpcclient-go/plugins"
	version "simplerpc/zrpcclient-go/typed/version"
)

type Clientset interface {
	Direct() zrpc.Client

	Version() version.Version

	Plugins() plugins.Plugins
}

type clientset struct {
	// direct client to request
	direct zrpc.Client

	version version.Version

	plugins plugins.Plugins
}

func (cs *clientset) Direct() zrpc.Client {
	return cs.direct
}

func (cs *clientset) Version() version.Version {
	return cs.version
}

func (cs *clientset) Plugins() plugins.Plugins {
	return cs.plugins
}

func NewClientset(cli zrpc.Client) (Clientset, error) {
	cs := clientset{
		direct:  cli,
		version: version.NewVersion(cli),
		plugins: plugins.NewPlugins(cli),
	}

	return &cs, nil
}
