// Code generated by jzero. DO NOT EDIT.

package model

import (
	"github.com/eddieowens/opts"
	"github.com/jzero-io/jzero/core/stores/modelx"
	"github.com/zeromicro/go-zero/core/stores/sqlx"

	"simplegateway-with-model-redis/internal/model/user"
)

type Model struct {
	User user.UserModel
}

func NewModel(conn sqlx.SqlConn, op ...opts.Opt[modelx.ModelOpts]) Model {

	return Model{
		User: user.NewUserModel(conn, op...),
	}
}
