// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: version.proto

package server

import (
	"context"

	"simplerpc/internal/logic/version"
	"simplerpc/internal/pb/versionpb"
	"simplerpc/internal/svc"
)

type Version struct {
	svcCtx *svc.ServiceContext
	versionpb.UnimplementedVersionServer
}

func NewVersion(svcCtx *svc.ServiceContext) *Version {
	return &Version{
		svcCtx: svcCtx,
	}
}

func (s *Version) Say(ctx context.Context, in *versionpb.GetRequest) (*versionpb.GetResponse, error) {
	l := versionlogic.NewSay(ctx, s.svcCtx)
	return l.Say(in)
}
