// Code generated by jzero. DO NOT EDIT.
package version

import (
	"time"
)

var (
	_ = time.Now()
)

type GetVersionRequest struct {
}

type GetVersionResponse struct {
	Version   string `json:"version"`
	GoVersion string `json:"goVersion"`
	Commit    string `json:"commit"`
	Date      string `json:"date"`
}
