// Code generated by jzero. DO NOT EDIT.

package simpleapi_with_model_redis_go

import (
	"github.com/jzero-io/jzero/core/restc"

	builtin "simpleapi-with-model-redis/simpleapi-with-model-redis-go/typed/builtin"
)

type Clientset interface {
	Direct() restc.Client

	Builtin() builtin.Builtin
}

type clientset struct {
	// direct client to request
	direct restc.Client

	builtin builtin.Builtin
}

func (cs *clientset) Direct() restc.Client {
	return cs.direct
}

func (cs *clientset) Builtin() builtin.Builtin {
	return cs.builtin
}

func NewClientset(cli restc.Client) (Clientset, error) {
	cs := clientset{
		direct:  cli,
		builtin: builtin.NewBuiltin(cli),
	}

	return &cs, nil
}
