// Code generated by jzero. DO NOT EDIT.

package zrpcclient_go

import (
	"github.com/zeromicro/go-zero/zrpc"

	hello "simplerpc-goctl/zrpcclient-go/typed/hello"
)

type Clientset interface {
	Hello() hello.Hello
}

type clientset struct {
	hello hello.Hello
}

func (cs *clientset) Hello() hello.Hello {
	return cs.hello
}

func NewClientset(cli zrpc.Client) (Clientset, error) {
	cs := clientset{
		hello: hello.NewHello(cli),
	}

	return &cs, nil
}
