// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: version.proto

package version

import (
	"context"

	"simplerpc/zrpcclient-go/model/pb/versionpb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	VersionRequest  = versionpb.VersionRequest
	VersionResponse = versionpb.VersionResponse

	Version interface {
	}

	defaultVersion struct {
		cli zrpc.Client
	}
)

func NewVersion(cli zrpc.Client) Version {
	return &defaultVersion{
		cli: cli,
	}
}
