// Code generated by jzero. DO NOT EDIT.

package zrpcclient_go

import (
	"github.com/zeromicro/go-zero/zrpc"

	version "simplegateway/zrpcclient-go/typed/version"
)

type Clientset interface {
	Version() version.Version
}

type clientset struct {
	version version.Version
}

func (cs *clientset) Version() version.Version {
	return cs.version
}

func NewClientset(cli zrpc.Client) (Clientset, error) {
	cs := clientset{
		version: version.NewVersion(cli),
	}

	return &cs, nil
}
