// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package server

import (
	"context"

	userlogic "simplegateway/internal/logic/user"
	"simplegateway/internal/svc"
	"simplegateway/internal/types/user"
)

type User struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUser(svcCtx *svc.ServiceContext) *User {
	return &User{
		svcCtx: svcCtx,
	}
}

func (s *User) Create(ctx context.Context, in *user.CreateRequest) (*user.CreateResponse, error) {
	l := userlogic.NewCreate(ctx, s.svcCtx)
	return l.Create(in)
}
