// Code generated by jzero. DO NOT EDIT.

package model

import (
	"github.com/eddieowens/opts"
	"github.com/jzero-io/jzero/core/stores/modelx"
	"github.com/zeromicro/go-zero/core/stores/sqlx"

	"helloworld/internal/model/helloworld"
)

type Model struct {
	Helloworld helloworld.HelloworldModel
}

func NewModel(conn sqlx.SqlConn, op ...opts.Opt[modelx.ModelOpts]) Model {
	return Model{
		Helloworld: helloworld.NewHelloworldModel(conn, op...),
	}
}
