// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"gateway-sqlx/internal/logic/user"
	"gateway-sqlx/internal/pb/userpb"
	"gateway-sqlx/internal/svc"
)

type User struct {
	svcCtx *svc.ServiceContext
	userpb.UnimplementedUserServer
}

func NewUser(svcCtx *svc.ServiceContext) *User {
	return &User{
		svcCtx: svcCtx,
	}
}

func (s *User) CreateUser(ctx context.Context, in *userpb.CreateUserRequest) (*userpb.CreateUserResponse, error) {
	l := userlogic.NewCreateUser(ctx, s.svcCtx)
	return l.CreateUser(in)
}

func (s *User) ListUser(ctx context.Context, in *userpb.ListUserRequest) (*userpb.ListUserResponse, error) {
	l := userlogic.NewListUser(ctx, s.svcCtx)
	return l.ListUser(in)
}
