// Code generated by jzero. DO NOT EDIT.

package zrpcclient_go

import (
	"github.com/zeromicro/go-zero/zrpc"

	version "simplegateway-with-model-redis/zrpcclient-go/typed/version"
)

type Clientset interface {
	Direct() zrpc.Client

	Version() version.Version
}

type clientset struct {
	// direct client to request
	direct zrpc.Client

	version version.Version
}

func (cs *clientset) Direct() zrpc.Client {
	return cs.direct
}

func (cs *clientset) Version() version.Version {
	return cs.version
}

func NewClientset(cli zrpc.Client) (Clientset, error) {
	cs := clientset{
		direct:  cli,
		version: version.NewVersion(cli),
	}

	return &cs, nil
}
