// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: version.proto

package server

import (
	"context"

	versionlogic "simplegateway/internal/logic/version"
	"simplegateway/internal/svc"
	"simplegateway/internal/types/version"
)

type Version struct {
	svcCtx *svc.ServiceContext
	version.UnimplementedVersionServer
}

func NewVersion(svcCtx *svc.ServiceContext) *Version {
	return &Version{
		svcCtx: svcCtx,
	}
}

func (s *Version) Version(ctx context.Context, in *version.VersionRequest) (*version.VersionResponse, error) {
	l := versionlogic.NewVersion(ctx, s.svcCtx)
	return l.Version(in)
}
