// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4
// Source: version.proto

package server

import (
	"context"

	"simplegateway/internal/logic/version"
	"simplegateway/internal/pb/versionpb"
	"simplegateway/internal/svc"
)

type Version struct {
	svcCtx *svc.ServiceContext
	versionpb.UnimplementedVersionServer
}

func NewVersion(svcCtx *svc.ServiceContext) *Version {
	return &Version{
		svcCtx: svcCtx,
	}
}

func (s *Version) Version(ctx context.Context, in *versionpb.VersionRequest) (*versionpb.VersionResponse, error) {
	l := versionlogic.NewVersion(ctx, s.svcCtx)
	return l.Version(in)
}
