// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: helloworld.proto

package server

import (
	"context"

	helloworldlogic "helloworld/internal/logic/helloworld"
	"helloworld/internal/svc"
	"helloworld/internal/types/helloworld"
)

type Helloworld struct {
	svcCtx *svc.ServiceContext
	helloworld.UnimplementedHelloworldServer
}

func NewHelloworld(svcCtx *svc.ServiceContext) *Helloworld {
	return &Helloworld{
		svcCtx: svcCtx,
	}
}

func (s *Helloworld) Create(ctx context.Context, in *helloworld.CreateRequest) (*helloworld.CreateResponse, error) {
	l := helloworldlogic.NewCreate(ctx, s.svcCtx)
	return l.Create(in)
}
