CREATE TABLE IF NOT EXISTS T_system_dict_value
(
  id INT NOT NULL AUTO_INCREMENT,
  key_uuid VARCHAR(36) NOT NULL COMMENT 'key uuid',
  uuid VARCHAR(36) UNIQUE NOT NULL COMMENT 'uuid',
  label VARCHAR(100) NOT NULL COMMENT '字典名称（展示）',
  value VARCHAR(100) NOT NULL COMMENT '字典值',
  sort INT NOT NULL COMMENT '排序（升序）',
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间',
  update_time TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  remarks VARCHAR(255) DEFAULT '',
  PRIMARY KEY(id)
)
