// Code generated by jzero. DO NOT EDIT.
// type: simpleapi_goctl_client

package simpleapi_goctl

import (
	"github.com/jzero-io/restc"
)

type SimpleapiGoctlInterface interface {
	RESTClient() restc.Interface
	
	VersionGetter
	
}

type SimpleapiGoctlClient struct {
	restClient restc.Interface
}

func (x *SimpleapiGoctlClient) RESTClient() restc.Interface {
	if x == nil {
		return nil
	}
	return x.restClient
}

func (x *SimpleapiGoctlClient) Version() VersionInterface {
	return newVersionClient(x)
}


// NewForConfig creates a new SimpleapiGoctlClient for the given config.
func NewForConfig(x *restc.RESTClient) (*SimpleapiGoctlClient, error) {
	return &SimpleapiGoctlClient{x}, nil
}