// Code generated by jzero. DO NOT EDIT.
// type: version

package simpleapi_goctl

import (
	"context"
	"simpleapi-goctl/simpleapi-goctl-go/model/simpleapi_goctl/types"

	"github.com/jzero-io/restc"
)

var (
	_ = context.Background()
)

type VersionGetter interface {
	Version() VersionInterface
}

type VersionInterface interface {
	// API /api/v1/version
	GetVersion(ctx context.Context, param types.GetVersionRequest) (*types.GetVersionResponse, error)

	VersionExpansion
}

type versionClient struct {
	client restc.Interface
}

func newVersionClient(c *SimpleapiGoctlClient) *versionClient {
	return &versionClient{
		client: c.RESTClient(),
	}
}

func (x *versionClient) GetVersion(ctx context.Context, param types.GetVersionRequest) (*types.GetVersionResponse, error) {
	var resp *types.GetVersionResponse
	err := x.client.Verb("GET").
		SubPath(
			"/api/v1/version",
		).
		Params().
		Do(ctx).
		Into(&resp, true)

	if err != nil {
		return nil, err
	}

	return resp, nil
}
