// Code generated by jzero. DO NOT EDIT.
package handler

import (
	"net/http"
	"time"

	"github.com/zeromicro/go-zero/rest"

	helloworld "simpleapi/plugins/helloworld/internal/handler/helloworld"
	"simpleapi/plugins/helloworld/internal/svc"
)

var (
	_ = http.StatusOK
	_ = time.Now()
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	{
		server.AddRoutes(
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: helloworld.Create(serverCtx),
				},
			},
			rest.WithPrefix("/api/helloworld"),
		)
	}

}
