// Code generated by jzero. DO NOT EDIT.
package handler

import (
	"net/http"
	"time"

	"github.com/zeromicro/go-zero/rest"

	helloworldversion "helloworld/internal/handler/helloworldversion"
	"helloworld/internal/svc"
)

var (
	_ = http.StatusOK
	_ = time.Now()
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	{
		server.AddRoutes(
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/version",
					Handler: helloworldversion.Version(serverCtx),
				},
			},
			rest.WithPrefix("/api/v1/helloworld"),
		)
	}

}
