version: '3'
services:
  mysql:
    image: "mysql:8.0"
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=test
    volumes:
      - ./data/mysql_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"