// Code generated by jzero. DO NOT EDIT.
package plugins

import (
	helloworld "helloworld/serverless"

	"github.com/zeromicro/go-zero/rest"

	"simpleapi/internal/svc"
)

func LoadPlugins(server *rest.Server, svcCtx *svc.ServiceContext) {

	{
		serverless := helloworld.New()
		serverless.HandlerFunc(server, serverless.SvcCtx)
	}

}
