// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: helloworld.proto

package helloworld

import (
	"context"

	"simplerpc/zrpcclient-go/plugins/helloworld/model/types/helloworld"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateRequest  = helloworld.CreateRequest
	CreateResponse = helloworld.CreateResponse

	Helloworld interface {
		Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	}

	defaultHelloworld struct {
		cli zrpc.Client
	}
)

func NewHelloworld(cli zrpc.Client) Helloworld {
	return &defaultHelloworld{
		cli: cli,
	}
}

func (m *defaultHelloworld) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	client := helloworld.NewHelloworldClient(m.cli.Conn())
	return client.Create(ctx, in, opts...)
}
