// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	systemdict "api-gorm-muti-database/internal/handler/system/dict"
	systemversion "api-gorm-muti-database/internal/handler/system/version"
	"api-gorm-muti-database/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/system/dict/:uuid/list",
				Handler: systemdict.ListValue(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/system/dict/create",
				Handler: systemdict.Create(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/system/dict/key/list",
				Handler: systemdict.ListKey(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/system/dict/value/delete/:uuid",
				Handler: systemdict.DeleteValue(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/system/dict/value/edit/:uuid",
				Handler: systemdict.EditValue(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/version",
				Handler: systemversion.Get(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
