// Code generated by goctl. Templates Edited by jzero. DO NOT EDIT.

package helloworld

import (
	"context"
	"database/sql"
	"slices"
	"strings"

	"github.com/eddieowens/opts"
	"github.com/huandu/go-sqlbuilder"
	"github.com/jzero-io/jzero/core/stores/condition"
	"github.com/jzero-io/jzero/core/stores/modelx"
	"github.com/spf13/cast"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
)

var (
	helloworldFieldNames               []string
	helloworldRows                     string
	helloworldRowsExpectAutoFieldNames []string
	helloworldRowsExpectAutoSet        string
)

const (
	Id condition.Field = "id"
)

func initHelloworldVars(flavor sqlbuilder.Flavor) {
	helloworldFieldNames = condition.RawFieldNamesWithFlavor(flavor, &Helloworld{})
	helloworldRows = strings.Join(helloworldFieldNames, ",")
	helloworldRowsExpectAutoFieldNames = condition.RemoveIgnoreColumnsWithFlavor(flavor, helloworldFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`")
	helloworldRowsExpectAutoSet = strings.Join(helloworldRowsExpectAutoFieldNames, ",")
}

type (
	helloworldModel interface {
		// Insert insert a new record into the database.
		// Deprecated: use InsertV2 instead.
		Insert(ctx context.Context, session sqlx.Session, data *Helloworld) (sql.Result, error)
		InsertV2(ctx context.Context, session sqlx.Session, data *Helloworld) error
		FindOne(ctx context.Context, session sqlx.Session, id int64) (*Helloworld, error)
		Update(ctx context.Context, session sqlx.Session, data *Helloworld) error
		Delete(ctx context.Context, session sqlx.Session, id int64) error

		// custom interface generated by jzero
		WithTable(f func(table string) string) helloworldModel
		BulkInsert(ctx context.Context, session sqlx.Session, datas []*Helloworld) error
		FindByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*Helloworld, error)
		// FindSelectedColumnsByCondition: return selected fields by condition
		// Deprecated: Use FindFieldsByCondition
		FindSelectedColumnsByCondition(ctx context.Context, session sqlx.Session, columns []string, conditions ...condition.Condition) ([]*Helloworld, error)
		FindFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) ([]*Helloworld, error)
		FindOneByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (*Helloworld, error)
		FindOneFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) (*Helloworld, error)
		CountByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (int64, error)
		PageByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*Helloworld, int64, error)
		UpdateFieldsByCondition(ctx context.Context, session sqlx.Session, field map[string]any, conditions ...condition.Condition) error
		DeleteByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) error
	}

	defaultHelloworldModel struct {
		cachedConn sqlc.CachedConn
		conn       sqlx.SqlConn
		flavor     sqlbuilder.Flavor
		table      string
	}

	Helloworld struct {
		Id int64 `db:"id"`
	}
)

func newHelloworldModel(conn sqlx.SqlConn, op ...opts.Opt[modelx.ModelOpts]) *defaultHelloworldModel {
	o := opts.DefaultApply(op...)
	var cachedConn sqlc.CachedConn
	if len(o.CacheConf) > 0 {
		cachedConn = sqlc.NewConn(conn, o.CacheConf, o.CacheOpts...)
	}
	if o.CachedConn != nil {
		cachedConn = *o.CachedConn
	}

	initHelloworldVars(o.Flavor)

	return &defaultHelloworldModel{
		cachedConn: cachedConn,
		conn:       conn,
		flavor:     o.Flavor,
		table:      condition.QuoteWithFlavor(o.Flavor, "helloworld"),
	}
}

// NewOriginalHelloworldModel returns a original model for the database table.
func NewOriginalHelloworldModel(conn sqlx.SqlConn) HelloworldModel {
	return &customHelloworldModel{
		defaultHelloworldModel: newHelloworldModel(conn),
	}
}

func (m *defaultHelloworldModel) clone() *defaultHelloworldModel {
	return &defaultHelloworldModel{
		cachedConn: m.cachedConn,
		conn:       m.conn,
		table:      m.table,
		flavor:     m.flavor,
	}
}

func (m *defaultHelloworldModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	sb := sqlbuilder.DeleteFrom(m.table)
	sb.Where(sb.EQ(condition.QuoteWithFlavor(m.flavor, "`id`"), id))
	statement, args := sb.BuildWithFlavor(m.flavor)
	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *defaultHelloworldModel) FindOne(ctx context.Context, session sqlx.Session, id int64) (*Helloworld, error) {
	sb := sqlbuilder.Select(helloworldRows).From(m.table)
	sb.Where(sb.EQ(condition.QuoteWithFlavor(m.flavor, "`id`"), id))
	sb.Limit(1)
	sql, args := sb.BuildWithFlavor(m.flavor)
	var resp Helloworld
	var err error
	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, sql, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, sql, args...)
	}
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultHelloworldModel) Insert(ctx context.Context, session sqlx.Session, data *Helloworld) (sql.Result, error) {
	statement, args := sqlbuilder.NewInsertBuilder().
		InsertInto(m.table).
		Cols(helloworldRowsExpectAutoSet).
		Values().BuildWithFlavor(m.flavor)
	if session != nil {
		return session.ExecCtx(ctx, statement, args...)
	}
	return m.conn.ExecCtx(ctx, statement, args...)
}

func (m *defaultHelloworldModel) InsertV2(ctx context.Context, session sqlx.Session, data *Helloworld) error {
	var statement string
	var args []any
	if sqlbuilder.DefaultFlavor == sqlbuilder.PostgreSQL || sqlbuilder.DefaultFlavor == sqlbuilder.SQLite {
		statement, args = sqlbuilder.NewInsertBuilder().
			InsertInto(m.table).
			Cols(helloworldRowsExpectAutoSet).
			Values().Returning("id").BuildWithFlavor(m.flavor)
	} else {
		statement, args = sqlbuilder.NewInsertBuilder().
			InsertInto(m.table).
			Cols(helloworldRowsExpectAutoSet).
			Values().BuildWithFlavor(m.flavor)
	}
	var primaryKey int64
	var err error
	if session != nil {
		if sqlbuilder.DefaultFlavor == sqlbuilder.PostgreSQL || sqlbuilder.DefaultFlavor == sqlbuilder.SQLite {
			err = session.QueryRowCtx(ctx, &primaryKey, statement, args...)
			if err != nil {
				return err
			}
		} else {
			result, err := session.ExecCtx(ctx, statement, args...)
			if err != nil {
				return err
			}
			lastInsertId, err := result.LastInsertId()
			if err != nil {
				return err
			}
			primaryKey = int64(lastInsertId)
		}
	} else {
		if sqlbuilder.DefaultFlavor == sqlbuilder.PostgreSQL || sqlbuilder.DefaultFlavor == sqlbuilder.SQLite {
			err = m.conn.QueryRowCtx(ctx, &primaryKey, statement, args...)
		} else {
			result, err := m.conn.ExecCtx(ctx, statement, args...)
			if err != nil {
				return err
			}
			lastInsertId, err := result.LastInsertId()
			if err != nil {
				return err
			}
			primaryKey = int64(lastInsertId)
		}
	}
	data.Id = primaryKey
	return err
}

func (m *defaultHelloworldModel) Update(ctx context.Context, session sqlx.Session, data *Helloworld) error {
	sb := sqlbuilder.Update(m.table)
	var assigns []string
	if slices.Contains(helloworldRowsExpectAutoFieldNames, condition.QuoteWithFlavor(m.flavor, "id")) {
		assigns = append(assigns, sb.Assign(condition.QuoteWithFlavor(m.flavor, "id"), data.Id))
	}

	sb.Set(assigns...)
	sb.Where(sb.EQ(condition.QuoteWithFlavor(m.flavor, "`id`"), data.Id))
	statement, args := sb.BuildWithFlavor(m.flavor)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *defaultHelloworldModel) withTableFields(fields ...string) []string {
	var withTableFields []string
	for _, col := range fields {
		if strings.Contains(col, ".") {
			withTableFields = append(withTableFields, condition.QuoteWithFlavor(m.flavor, col))
		} else {
			withTableFields = append(withTableFields, m.table+"."+condition.QuoteWithFlavor(m.flavor, col))
		}
	}
	return withTableFields
}

func (m *customHelloworldModel) WithTable(f func(table string) string) helloworldModel {
	mc := &customHelloworldModel{
		defaultHelloworldModel: m.clone(),
	}
	mc.table = condition.QuoteWithFlavor(m.flavor, f(m.table))
	return mc
}

func (m *customHelloworldModel) BulkInsert(ctx context.Context, session sqlx.Session, datas []*Helloworld) error {
	if len(datas) == 0 {
		return nil
	}

	sb := sqlbuilder.InsertInto(m.table)
	sb.Cols(helloworldRowsExpectAutoSet)
	for _, data := range datas {
		sb.Values()
	}
	statement, args := sb.BuildWithFlavor(m.flavor)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}

func (m *customHelloworldModel) FindFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) ([]*Helloworld, error) {
	if len(fields) == 0 {
		fields = condition.ToFieldSlice(helloworldFieldNames)
	}

	statement, args := condition.BuildSelectWithFlavor(m.flavor, sqlbuilder.Select(m.withTableFields(cast.ToStringSlice(fields)...)...).From(m.table), conditions...)

	var resp []*Helloworld
	var err error

	if session != nil {
		err = session.QueryRowsPartialCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowsPartialCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (m *customHelloworldModel) FindSelectedColumnsByCondition(ctx context.Context, session sqlx.Session, columns []string, conditions ...condition.Condition) ([]*Helloworld, error) {
	return m.FindFieldsByCondition(ctx, session, condition.ToFieldSlice(columns), conditions...)
}

func (m *customHelloworldModel) FindByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*Helloworld, error) {
	return m.FindSelectedColumnsByCondition(ctx, session, helloworldFieldNames, conditions...)
}

func (m *customHelloworldModel) CountByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (int64, error) {
	var countconditions []condition.Condition
	for _, cond := range conditions {
		if cond.Operator != condition.Limit && cond.Operator != condition.Offset && cond.Operator != condition.OrderBy && cond.Operator != condition.OrderByDesc && cond.Operator != condition.OrderByAsc {
			countconditions = append(countconditions, cond)
		}
	}

	statement, args := condition.BuildSelectWithFlavor(m.flavor, sqlbuilder.Select("count(*)").From(m.table), countconditions...)

	var (
		total int64
		err   error
	)

	if session != nil {
		err = session.QueryRowCtx(ctx, &total, statement, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &total, statement, args...)
	}
	if err != nil {
		return 0, err
	}
	return total, nil
}

func (m *customHelloworldModel) FindOneByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) (*Helloworld, error) {
	return m.FindOneFieldsByCondition(ctx, session, condition.ToFieldSlice(helloworldFieldNames), conditions...)
}

func (m *customHelloworldModel) FindOneFieldsByCondition(ctx context.Context, session sqlx.Session, fields []condition.Field, conditions ...condition.Condition) (*Helloworld, error) {
	statement, args := condition.BuildSelectWithFlavor(m.flavor, sqlbuilder.Select(m.withTableFields(cast.ToStringSlice(helloworldFieldNames)...)...).From(m.table).Limit(1), conditions...)

	var resp Helloworld
	var err error

	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

func (m *customHelloworldModel) PageByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) ([]*Helloworld, int64, error) {
	statement, args := condition.BuildSelectWithFlavor(m.flavor, sqlbuilder.Select(m.withTableFields(helloworldFieldNames...)...).From(m.table), conditions...)

	var resp []*Helloworld
	var err error

	if session != nil {
		err = session.QueryRowsCtx(ctx, &resp, statement, args...)
	} else {
		err = m.conn.QueryRowsCtx(ctx, &resp, statement, args...)
	}
	if err != nil {
		return nil, 0, err
	}

	total, err := m.CountByCondition(ctx, session, conditions...)
	if err != nil {
		return nil, 0, err
	}

	return resp, total, nil
}

func (m *customHelloworldModel) UpdateFieldsByCondition(ctx context.Context, session sqlx.Session, data map[string]any, conditions ...condition.Condition) error {
	if data == nil {
		return nil
	}

	statement, args := condition.BuildUpdateWithFlavor(m.flavor, sqlbuilder.Update(m.table), data, conditions...)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	if err != nil {
		return err
	}
	return nil
}

func (m *customHelloworldModel) DeleteByCondition(ctx context.Context, session sqlx.Session, conditions ...condition.Condition) error {
	if len(conditions) == 0 {
		return nil
	}
	statement, args := condition.BuildDeleteWithFlavor(m.flavor, sqlbuilder.DeleteFrom(m.table), conditions...)

	var err error
	if session != nil {
		_, err = session.ExecCtx(ctx, statement, args...)
	} else {
		_, err = m.conn.ExecCtx(ctx, statement, args...)
	}
	return err
}
