// Code generated by goctl. DO NOT EDIT.

package products

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	productsFieldNames          = builder.RawFieldNames(&Products{})
	productsRows                = strings.Join(productsFieldNames, ",")
	productsRowsExpectAutoSet   = strings.Join(stringx.Remove(productsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	productsRowsWithPlaceHolder = strings.Join(stringx.Remove(productsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	productsModel interface {
		Insert(ctx context.Context, data *Products) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Products, error)
		Update(ctx context.Context, data *Products) error
		Delete(ctx context.Context, id int64) error
	}

	defaultProductsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Products struct {
		Id        int64          `db:"id"`
		CreatedAt sql.NullTime   `db:"created_at"`
		UpdatedAt sql.NullTime   `db:"updated_at"`
		DeletedAt sql.NullTime   `db:"deleted_at"`
		Code      sql.NullString `db:"code"`
		Price     sql.NullInt64  `db:"price"`
		Remark    sql.NullString `db:"remark"`
	}
)

func newProductsModel(conn sqlx.SqlConn) *defaultProductsModel {
	return &defaultProductsModel{
		conn:  conn,
		table: strings.ReplaceAll("`products`", "`", ""),
	}
}

func (m *defaultProductsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	query = strings.ReplaceAll(query, "`", "")
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultProductsModel) FindOne(ctx context.Context, id int64) (*Products, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", productsRows, m.table)
	query = strings.ReplaceAll(query, "`", "")
	var resp Products
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductsModel) Insert(ctx context.Context, data *Products) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, productsRowsExpectAutoSet)
	query = strings.ReplaceAll(query, "`", "")
	ret, err := m.conn.ExecCtx(ctx, query, data.DeletedAt, data.Code, data.Price, data.Remark)
	return ret, err
}

func (m *defaultProductsModel) Update(ctx context.Context, data *Products) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, productsRowsWithPlaceHolder)
	query = strings.ReplaceAll(query, "`", "")
	_, err := m.conn.ExecCtx(ctx, query, data.DeletedAt, data.Code, data.Price, data.Remark, data.Id)
	return err
}

func (m *defaultProductsModel) tableName() string {
	return m.table
}
