// Code generated by goctl. DO NOT EDIT.

package products

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	productsFieldNames          = builder.RawFieldNames(&Products{})
	productsRows                = strings.Join(productsFieldNames, ",")
	productsRowsExpectAutoSet   = strings.Join(stringx.Remove(productsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	productsRowsWithPlaceHolder = strings.Join(stringx.Remove(productsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheProductsIdPrefix = "jaronniecache:products:id:"
)

type (
	productsModel interface {
		Insert(ctx context.Context, data *Products) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Products, error)
		Update(ctx context.Context, data *Products) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultProductsModel struct {
		sqlc.CachedConn
		table string
	}

	Products struct {
		Id        uint64         `db:"id"`
		CreatedAt sql.NullTime   `db:"created_at"`
		UpdatedAt sql.NullTime   `db:"updated_at"`
		DeletedAt sql.NullTime   `db:"deleted_at"`
		Code      sql.NullString `db:"code"`
		Price     sql.NullInt64  `db:"price"`
		Remark    sql.NullString `db:"remark"`
	}
)

func newProductsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultProductsModel {
	return &defaultProductsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      strings.ReplaceAll("`products`", "`", ""),
	}
}

func (m *defaultProductsModel) Delete(ctx context.Context, id uint64) error {
	productsIdKey := fmt.Sprintf("%s%v", cacheProductsIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		query = strings.ReplaceAll(query, "`", "")
		return conn.ExecCtx(ctx, query, id)
	}, productsIdKey)
	return err
}

func (m *defaultProductsModel) FindOne(ctx context.Context, id uint64) (*Products, error) {
	productsIdKey := fmt.Sprintf("%s%v", cacheProductsIdPrefix, id)
	var resp Products
	err := m.QueryRowCtx(ctx, &resp, productsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", productsRows, m.table)
		query = strings.ReplaceAll(query, "`", "")
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductsModel) Insert(ctx context.Context, data *Products) (sql.Result, error) {
	productsIdKey := fmt.Sprintf("%s%v", cacheProductsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, productsRowsExpectAutoSet)
		query = strings.ReplaceAll(query, "`", "")
		return conn.ExecCtx(ctx, query, data.DeletedAt, data.Code, data.Price, data.Remark)
	}, productsIdKey)
	return ret, err
}

func (m *defaultProductsModel) Update(ctx context.Context, data *Products) error {
	productsIdKey := fmt.Sprintf("%s%v", cacheProductsIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, productsRowsWithPlaceHolder)
		query = strings.ReplaceAll(query, "`", "")
		return conn.ExecCtx(ctx, query, data.DeletedAt, data.Code, data.Price, data.Remark, data.Id)
	}, productsIdKey)
	return err
}

func (m *defaultProductsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheProductsIdPrefix, primary)
}

func (m *defaultProductsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", productsRows, m.table)
	query = strings.ReplaceAll(query, "`", "")
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultProductsModel) tableName() string {
	return m.table
}
