// Code generated by goctl. DO NOT EDIT.
// Source: hello_v2.proto

package server

import (
	"context"

	"simplegateway/internal/logic/hellov2"
	"simplegateway/internal/pb/hellov2pb"
	"simplegateway/internal/svc"
)

type Hellov2 struct {
	svcCtx *svc.ServiceContext
	hellov2pb.UnimplementedHellov2Server
}

func NewHellov2(svcCtx *svc.ServiceContext) *Hellov2 {
	return &Hellov2{
		svcCtx: svcCtx,
	}
}

func (s *Hellov2) SayHello(ctx context.Context, in *hellov2pb.Empty) (*hellov2pb.SayHelloResponse, error) {
	l := hellov2logic.NewSayHello(ctx, s.svcCtx)
	return l.SayHello(in)
}
