// Code generated by jzero. DO NOT EDIT.
// type: clientset

package simplegateway_go

import (
	"github.com/jzero-io/restc"
	"simplegateway/simplegateway-go/typed"

	
)

type Interface interface {
	Direct() typed.DirectInterface

	
}

type Clientset struct {
	// direct client to request
	direct *typed.DirectClient

	
}

func (x *Clientset) Direct() typed.DirectInterface {
	return x.direct
}

func NewClientWithOptions(ops ...restc.Opt) (*Clientset, error) {
	c := &restc.RESTClient{}
	for _, op := range ops {
		if err := op(c); err != nil {
			return nil, err
		}
	}
	configShallowCopy := *c
	var cs Clientset
	var err error
	cs.direct, err = typed.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	
	return &cs, nil
}