// Code generated by jzero. DO NOT EDIT.
// type: builtin

package builtin

import (
	"context"

	"github.com/jzero-io/jzero/core/restc"

	"simpleapi/simpleapi-go/model/builtin"
)

var (
	_ = context.Background()
)

type (
	Builtin interface {
		// Swagger
		// GET:swagger
		Swagger() (*restc.Request, error)
		// Version
		// GET:version
		Version(ctx context.Context, in *builtin.VersionRequest) (*builtin.VersionResponse, error)
	}

	builtinClient struct {
		client restc.Client
	}
)

func NewBuiltin(c restc.Client) Builtin {
	return &builtinClient{
		client: c,
	}
}

func (x *builtinClient) Swagger() (*restc.Request, error) {
	request := x.client.Verb("GET").
		Path(
			"swagger",
		)
	return request, nil
}
func (x *builtinClient) Version(ctx context.Context, in *builtin.VersionRequest) (*builtin.VersionResponse, error) {
	var resp *builtin.VersionResponse
	err := x.client.Verb("GET").
		Path(
			"version",
		).
		Params().
		Do(ctx).
		Into(&resp, nil)

	if err != nil {
		return nil, err
	}

	return resp, nil
}
