// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	product "api-gorm-sqlx-muti-database/internal/handler/product"
	"api-gorm-sqlx-muti-database/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/pruduct/:id",
				Handler: product.Get(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/pruduct/create",
				Handler: product.Create(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
