// Code generated by jzero. DO NOT EDIT.
// type: Version

package version

import (
	"context"

	"github.com/jzero-io/jzero/core/restc"

	"simplegateway/simplegateway-go/model/pb/versionpb"
)

var (
	_ = context.Background()
)

type (
	Version interface {
		// Version
		// GET:/api/v1/version
		Version(ctx context.Context, in *versionpb.VersionRequest) (*versionpb.VersionResponse, error)
	}

	versionClient struct {
		client restc.Client
	}
)

func NewVersion(c restc.Client) Version {
	return &versionClient{
		client: c,
	}
}

func (x *versionClient) Version(ctx context.Context, in *versionpb.VersionRequest) (*versionpb.VersionResponse, error) {
	var resp *versionpb.VersionResponse
	err := x.client.Verb("GET").
		Path(
			"/api/v1/version",
		).
		Params().
		Do(ctx).
		Into(&resp, nil)

	if err != nil {
		return nil, err
	}

	return resp, nil
}
