// Code generated by jzero. DO NOT EDIT.
// type: simplegateway_client

package simplegateway

import (
	"github.com/jzero-io/restc"
)

type SimplegatewayInterface interface {
	RESTClient() restc.Interface
	
	HelloGetter
	VersionGetter
	
}

type SimplegatewayClient struct {
	restClient restc.Interface
}

func (x *SimplegatewayClient) RESTClient() restc.Interface {
	if x == nil {
		return nil
	}
	return x.restClient
}

func (x *SimplegatewayClient) Hello() HelloInterface {
	return newHelloClient(x)
}

func (x *SimplegatewayClient) Version() VersionInterface {
	return newVersionClient(x)
}


// NewForConfig creates a new SimplegatewayClient for the given config.
func NewForConfig(x *restc.RESTClient) (*SimplegatewayClient, error) {
	return &SimplegatewayClient{x}, nil
}