// Code generated by jzero. DO NOT EDIT.
// type: Version

package simplegateway

import (
	"context"
	"simplegateway/simplegateway-go/model/simplegateway/pb/versionpb"

	"github.com/jzero-io/restc"
)

var (
	_ = context.Background()
)

type VersionGetter interface {
	Version() VersionInterface
}

type VersionInterface interface {
	// API /api/v1/version
	Version(ctx context.Context, param *versionpb.VersionRequest) (*versionpb.VersionResponse, error)

	VersionExpansion
}

type VersionClient struct {
	client restc.Interface
}

func newVersionClient(c *SimplegatewayClient) *VersionClient {
	return &VersionClient{
		client: c.RESTClient(),
	}
}

func (x *VersionClient) Version(ctx context.Context, param *versionpb.VersionRequest) (*versionpb.VersionResponse, error) {
	var resp *versionpb.VersionResponse
	err := x.client.Verb("GET").
		SubPath(
			"/api/v1/version",
		).
		Params().
		Do(ctx).
		Into(&resp, true)

	if err != nil {
		return nil, err
	}

	return resp, nil
}
