// Code generated by goctl. Templates Edited by jzero. DO NOT EDIT.

package helloworld

import (
	"net/http"

	"github.com/zeromicro/go-zero/rest/httpx"

	"simpleapi/plugins/helloworld/internal/logic/helloworld"
	"simpleapi/plugins/helloworld/internal/svc"
	types "simpleapi/plugins/helloworld/internal/types/helloworld"
)

func Create(svcCtx *svc.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.CreateRequest
		if err := httpx.Parse(r, &req); err != nil {
			httpx.ErrorCtx(r.Context(), w, err)
			return
		}

		l := helloworld.NewCreate(r.Context(), svcCtx, r)
		resp, err := l.Create(&req)
		if err != nil {
			httpx.ErrorCtx(r.Context(), w, err)
		} else {
			httpx.OkJsonCtx(r.Context(), w, resp)
		}
	}
}
