// Code generated by goctl. DO NOT EDIT.
// Source: hello.proto

package server

import (
	"context"

	"simplegateway/internal/logic/hello"
	"simplegateway/internal/pb/hellopb"
	"simplegateway/internal/svc"
)

type HelloServer struct {
	svcCtx *svc.ServiceContext
	hellopb.UnimplementedHelloServer
}

func NewHelloServer(svcCtx *svc.ServiceContext) *HelloServer {
	return &HelloServer{
		svcCtx: svcCtx,
	}
}

func (s *HelloServer) SayHello(ctx context.Context, in *hellopb.Empty) (*hellopb.SayHelloResponse, error) {
	l := hellologic.NewSayHelloLogic(ctx, s.svcCtx)
	return l.SayHello(in)
}
