// Code generated by goctl. Templates Edited by jzero. DO NOT EDIT.

package version

import (
	"net/http"

	"github.com/zeromicro/go-zero/rest/httpx"

	"helloworld/internal/logic/version"
	"helloworld/internal/svc"
	types "helloworld/internal/types/version"
)

func Version(svcCtx *svc.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req types.VersionRequest
		if err := httpx.Parse(r, &req); err != nil {
			httpx.ErrorCtx(r.Context(), w, err)
			return
		}

		l := version.NewVersion(r.Context(), svcCtx, r)
		resp, err := l.Version(&req)
		if err != nil {
			httpx.ErrorCtx(r.Context(), w, err)
		} else {
			httpx.OkJsonCtx(r.Context(), w, resp)
		}
	}
}
