// Code generated by jzero. DO NOT EDIT.
// type: fake_clientset

package fake

import (
	"quickstart-go/typed"
	"quickstart-go/typed/fake"

    quickstart "quickstart-go/typed/quickstart"
    fakequickstart "quickstart-go/typed/quickstart/fake"

)

type Clientset struct {}

func (f *Clientset) Direct() typed.DirectInterface {
	return &fake.FakeDirect{}
}

func (f *Clientset) Quickstart() quickstart.QuickstartInterface {
    return &fakequickstart.FakeQuickstart{}
}

