// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateRequest struct {
}

type CreateResponse struct {
}
	Version   string `json:"version"`
	GoVersion string `json:"goVersion"`
	Commit    string `json:"commit"`
	Date      string `json:"date"`
}
