// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type GetRequest struct {
}

type GetResponse struct {
	Version   string `json:"version"`
	GoVersion string `json:"goVersion"`
	Commit    string `json:"commit"`
	Date      string `json:"date"`
}
