// Code generated by jzero. DO NOT EDIT.
package echo

import (
	"time"
)

var (
	_ = time.Now()
)

type EchoRequest struct {
	Message string `form:"message"`
}

type EchoResponse struct {
	Message string `json:"message"`
}
