// Code generated by goctl-types plugin. DO NOT EDIT.
package types

import (
	"time"
)

var (
	_ = time.Now()
)

type ListDictValueRequest struct {
	PageRequest
	Uuid string `form:"uuid"`
}

type PageRequest struct {
	Page int `form:"page"`
	Size int `form:"size"`
}

type ListDictValueResponse struct {
	Total int         `json:"total"`
	List  []DictValue `json:"list"`
}

type DictValue struct {
	KeyUuid    string `json:"keyUuid"`
	Uuid       string `json:"uuid"`
	Sort       int    `json:"sort"`  // 排序
	Label      string `json:"label"` // 字典项名称
	Value      string `json:"value"` // 字典值
	Language   string `json:"language"`
	Remarks    string `json:"remarks"` // 备注
	CreateTime string `json:"createTime"`
	UpdateTime string `json:"updateTime"`
}

type CreateDictRequest struct {
	CategoryCode string `json:"categoryCode"`          // 字典类型
	CategoryDesc string `json:"categoryDesc,optional"` // 类型描述
	Sort         int    `json:"sort"`                  // 排序
	Label        string `json:"label,optional"`        // 字典项名称
	Value        string `json:"value,optional"`        // 字典值
	Language     string `json:"language,optional"`
	Remarks      string `json:"remarks,optional"` // 备注
}

type ListDictKeyRequest struct {
	PageRequest
}

type ListDictKeyResponse struct {
	Total int       `json:"total"`
	List  []DictKey `json:"list"`
}

type DictKey struct {
	Uuid         string `json:"uuid"`
	CategoryCode string `json:"categoryCode"` // 字典类型
	CategoryDesc string `json:"categoryDesc"` // 类型描述
	Sort         int    `json:"sort"`         // 排序
}

type DeleteDictValueRequest struct {
	Uuid string `path:"uuid"`
}

type EditDictValueRequest struct {
	Uuid     string `path:"uuid"`
	Sort     int    `json:"sort"`  // 排序
	Label    string `json:"label"` // 字典项名称
	Value    string `json:"value"` // 字典值
	Language string `json:"language"`
	Remarks  string `json:"remarks"` // 备注
}
