// Code generated by goctl-types plugin. DO NOT EDIT.
package types

import (
	"time"
)

var (
	_ = time.Now()
)

type Empty struct {
}

type StrIdRequest struct {
	Id string `path:"id"`
}

type StrIdResponse struct {
	Id string `json:"id"`
}
