// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: v1/hello.proto

package hellopb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayRequest) Reset() {
	*x = SayRequest{}
	mi := &file_v1_hello_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayRequest) ProtoMessage() {}

func (x *SayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_hello_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayRequest.ProtoReflect.Descriptor instead.
func (*SayRequest) Descriptor() ([]byte, []int) {
	return file_v1_hello_proto_rawDescGZIP(), []int{0}
}

func (x *SayRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayResponse) Reset() {
	*x = SayResponse{}
	mi := &file_v1_hello_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayResponse) ProtoMessage() {}

func (x *SayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_hello_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayResponse.ProtoReflect.Descriptor instead.
func (*SayResponse) Descriptor() ([]byte, []int) {
	return file_v1_hello_proto_rawDescGZIP(), []int{1}
}

func (x *SayResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_v1_hello_proto protoreflect.FileDescriptor

const file_v1_hello_proto_rawDesc = "" +
	"\n" +
	"\x0ev1/hello.proto\x12\ahellopb\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\x1a;grpc-gateway/protoc-gen-openapiv2/options/annotations.proto\"0\n" +
	"\n" +
	"SayRequest\x12\"\n" +
	"\amessage\x18\x01 \x01(\tB\b\xfaB\x05r\x03\x98\x01\x05R\amessage\"'\n" +
	"\vSayResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2T\n" +
	"\x05Hello\x12K\n" +
	"\x03Say\x12\x13.hellopb.SayRequest\x1a\x14.hellopb.SayResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/hello/sayB\x17\x92A\x06\x12\x042\x02v1Z\f./pb/hellopbb\x06proto3"

var (
	file_v1_hello_proto_rawDescOnce sync.Once
	file_v1_hello_proto_rawDescData []byte
)

func file_v1_hello_proto_rawDescGZIP() []byte {
	file_v1_hello_proto_rawDescOnce.Do(func() {
		file_v1_hello_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_hello_proto_rawDesc), len(file_v1_hello_proto_rawDesc)))
	})
	return file_v1_hello_proto_rawDescData
}

var file_v1_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_hello_proto_goTypes = []any{
	(*SayRequest)(nil),  // 0: hellopb.SayRequest
	(*SayResponse)(nil), // 1: hellopb.SayResponse
}
var file_v1_hello_proto_depIdxs = []int32{
	0, // 0: hellopb.Hello.Say:input_type -> hellopb.SayRequest
	1, // 1: hellopb.Hello.Say:output_type -> hellopb.SayResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_hello_proto_init() }
func file_v1_hello_proto_init() {
	if File_v1_hello_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_hello_proto_rawDesc), len(file_v1_hello_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_hello_proto_goTypes,
		DependencyIndexes: file_v1_hello_proto_depIdxs,
		MessageInfos:      file_v1_hello_proto_msgTypes,
	}.Build()
	File_v1_hello_proto = out.File
	file_v1_hello_proto_goTypes = nil
	file_v1_hello_proto_depIdxs = nil
}
