// Code generated by jzero. DO NOT EDIT.
package plugins

import (
	"google.golang.org/grpc"

	"simplegateway-with-model-redis/internal/svc"
)

func LoadPlugins(grpcServer *grpc.Server, svcCtx *svc.ServiceContext) {}
