// Code generated by jzero. DO NOT EDIT.

package simplegateway_with_model_redis_go

import (
	"github.com/jzero-io/jzero/core/restc"

	version "simplegateway-with-model-redis/simplegateway-with-model-redis-go/typed/version"
)

type Clientset interface {
	Direct() restc.Client

	Version() version.Version
}

type clientset struct {
	// direct client to request
	direct restc.Client

	version version.Version
}

func (cs *clientset) Direct() restc.Client {
	return cs.direct
}

func (cs *clientset) Version() version.Version {
	return cs.version
}

func NewClientset(cli restc.Client) (Clientset, error) {
	cs := clientset{
		direct:  cli,
		version: version.NewVersion(cli),
	}

	return &cs, nil
}
