// Code generated by jzero. DO NOT EDIT.
package plugins

import (
	"github.com/zeromicro/go-zero/rest"

	"simpleapi-with-model-redis/internal/svc"
)

func LoadPlugins(server *rest.Server, svcCtx *svc.ServiceContext) {}
