syntax: v1

gen:
    hooks:
        before:
            - gorename simpleapi-serverless/server simpleapi-serverless/internal
        after:
            - gorename simpleapi-serverless/internal simpleapi-serverless/server
            - jzero gen swagger

    split-api-types-dir: true