// Code generated by jzero. DO NOT EDIT.

package server

import (
	"github.com/zeromicro/go-zero/core/service"
	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
	"google.golang.org/grpc/reflection"

	"simplegateway/internal/config"
	"simplegateway/internal/svc"

	hellosvr "simplegateway/internal/server/hello"
	hellov2svr "simplegateway/internal/server/hellov2"

	"simplegateway/internal/pb/hellopb"
	"simplegateway/internal/pb/hellov2pb"
)

func RegisterZrpc(c config.Config, ctx *svc.ServiceContext) *zrpc.RpcServer {
	s := zrpc.MustNewServer(c.Zrpc.RpcServerConf, func(grpcServer *grpc.Server) {
	    
		hellopb.RegisterHelloServer(grpcServer, hellosvr.NewHello(ctx))
		hellov2pb.RegisterHellov2Server(grpcServer, hellov2svr.NewHellov2(ctx))

		if c.Zrpc.Mode == service.DevMode || c.Zrpc.Mode == service.TestMode {
			reflection.Register(grpcServer)
		}
	})

	return s
}