// Code generated by jzero. DO NOT EDIT.
package handler

import (
	"net/http"
	"time"

	"github.com/zeromicro/go-zero/rest"

	user "simpleapi-with-model-redis/internal/handler/user"
	version "simpleapi-with-model-redis/internal/handler/version"
	"simpleapi-with-model-redis/internal/svc"
)

var (
	_ = http.StatusOK
	_ = time.Now()
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	{
		server.AddRoutes(
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: user.Create(serverCtx),
				},
			},
			rest.WithPrefix("/api/user"),
		)
	}
	{
		server.AddRoutes(
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/version",
					Handler: version.Version(serverCtx),
				},
			},
		)
	}

}
