// Code generated by jzero. DO NOT EDIT.

package simpleapi_go

import (
	"github.com/jzero-io/jzero/core/restc"

	"simpleapi/simpleapi-go/plugins"
	builtin "simpleapi/simpleapi-go/typed/builtin"
)

type Clientset interface {
	Direct() restc.Client

	Builtin() builtin.Builtin

	Plugins() plugins.Plugins
}

type clientset struct {
	// direct client to request
	direct restc.Client

	builtin builtin.Builtin

	plugins plugins.Plugins
}

func (cs *clientset) Direct() restc.Client {
	return cs.direct
}

func (cs *clientset) Builtin() builtin.Builtin {
	return cs.builtin
}

func (cs *clientset) Plugins() plugins.Plugins {
	return cs.plugins
}

func NewClientset(cli restc.Client) (Clientset, error) {
	cs := clientset{
		direct:  cli,
		builtin: builtin.NewBuiltin(cli),
		plugins: plugins.NewPlugins(cli),
	}

	return &cs, nil
}
