// Code generated by jzero. DO NOT EDIT.
// type: clientset

package simpleapi_go

import (
	"github.com/jzero-io/restc"
	"simpleapi/simpleapi-go/typed"

	"simpleapi/simpleapi-go/typed/simpleapi"
)

type Interface interface {
	Direct() typed.DirectInterface

	Simpleapi() simpleapi.SimpleapiInterface
}

type Clientset struct {
	// direct client to request
	direct *typed.DirectClient

	simpleapi *simpleapi.SimpleapiClient
}

func (x *Clientset) Direct() typed.DirectInterface {
	return x.direct
}

func (x *Clientset) Simpleapi() simpleapi.SimpleapiInterface {
	return x.simpleapi
}

func NewClientWithOptions(ops ...restc.Opt) (simpleapi.SimpleapiInterface, error) {
	c := &restc.RESTClient{}
	for _, op := range ops {
		if err := op(c); err != nil {
			return nil, err
		}
	}
	configShallowCopy := *c
	var cs Clientset
	var err error
	cs.direct, err = typed.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	cs.simpleapi, err = simpleapi.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	
	return cs.Simpleapi(), nil
}