// Code generated by jzero. DO NOT EDIT.

package simpleapi_go

import (
	version "simpleapi/simpleapi-go/typed/version"

	"github.com/jzero-io/restc"
)

type Clientset interface {
	Direct() restc.Client

	Version() version.Version
}

type clientset struct {
	// direct client to request
	direct restc.Client

	version version.Version
}

func (cs *clientset) Direct() restc.Client {
	return cs.direct
}

func (cs *clientset) Version() version.Version {
	return cs.version
}

func NewClientset(target string, ops ...restc.Opt) (Clientset, error) {
	restClient, err := restc.NewClient(target, ops...)
	if err != nil {
		return nil, err
	}

	cs := clientset{
		direct:  restClient,
		version: version.NewVersion(restClient),
	}

	return &cs, nil
}
