// Code generated by goctl-types plugin. DO NOT EDIT.
package types

import (
	"time"
)

var (
	_ = time.Now()
)

type IntIdPathRequest struct {
	Id int `path:"id"`
}

type GetProductResponse struct {
	Id     int    `json:"id"`
	Code   string `json:"code"`
	Price  int    `json:"price"`
	Remark string `json:"remark"`
}

type CreateProductRequest struct {
	Code   string `json:"code"`
	Price  int    `json:"price"`
	Remark string `json:"remark"`
}

type Empty struct {
}
