// Code generated by goctl-types plugin. DO NOT EDIT.
package types

import (
	"time"
)

var (
	_ = time.Now()
)

type PageRequest struct {
	Page int `form:"page"`
	Size int `form:"size"`
}

type StrIdPathRequest struct {
	Id string `path:"id"`
}

type StrIdResponse struct {
	Id string `json:"id"`
}
