version: '3'
services:
  mysql:
    image: "mysql:8.0"
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=ntls
    volumes:
      - ./desc/sql:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql
    restart: always
    ports:
      - "33060:3306"

  dameng8:
    image: jaronnie/dm8:dm8_20240422_rev215128_x86_rh6_64
    restart: always
    container_name: dameng8
    privileged: true
    environment:
      - PAGE_SIZE=16
      - LD_LIBRARY_PATH=/opt/dmdbms/bin
      - EXTENT_SIZE=32
      - BLANK_PAD_MODE=1
      - LOG_SIZE=1024
      - UNICODE_FLAG=1
      - LENGTH_IN_CHAR=1
      - INSTANCE_NAME=dameng8
    volumes:
      - ./desc/sql/dm8:/docker-entrypoint-initdb.d
      - ./dm8_data/dm8_data:/opt/dmdbms/data
    ports:
      - '30236:5236'

  jaeger:
    image: jaegertracing/all-in-one:1.6
    ports:
      - "14268:14268"
      - "16686:16686"
