// Code generated by jzero. DO NOT EDIT.
package handler

import (
	"net/http"
	"time"

	"github.com/zeromicro/go-zero/rest"

	builtin "simpleapi/internal/handler/builtin"
	"simpleapi/internal/svc"
)

var (
	_ = http.StatusOK
	_ = time.Now()
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	{
		server.AddRoutes(
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/swagger",
					Handler: builtin.Swagger(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/version",
					Handler: builtin.Version(serverCtx),
				},
			},
		)
	}

}
