// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: version.proto

package server

import (
	"simplerpc/internal/pb/versionpb"
	"simplerpc/internal/svc"
)

type Version struct {
	svcCtx *svc.ServiceContext
	versionpb.UnimplementedVersionServer
}

func NewVersion(svcCtx *svc.ServiceContext) *Version {
	return &Version{
		svcCtx: svcCtx,
	}
}
