// Code generated by jzero. DO NOT EDIT.

package server

import (
	"github.com/zeromicro/go-zero/core/service"
	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
	"google.golang.org/grpc/reflection"

	"simplegateway/plugins/helloworld/internal/config"
	"simplegateway/plugins/helloworld/internal/svc"

	helloworldsvr "simplegateway/plugins/helloworld/internal/server/helloworld"

	"simplegateway/plugins/helloworld/internal/types/helloworld"
)

// RegisterZrpc Deprecated: use RegisterZrpcServer instead.
func RegisterZrpc(c config.Config, ctx *svc.ServiceContext) *zrpc.RpcServer {
	s := zrpc.MustNewServer(c.Zrpc.RpcServerConf, func(grpcServer *grpc.Server) {
	    
		helloworld.RegisterHelloworldServer(grpcServer, helloworldsvr.NewHelloworld(ctx))

		if c.Zrpc.Mode == service.DevMode || c.Zrpc.Mode == service.TestMode {
			reflection.Register(grpcServer)
		}
	})

	return s
}

func RegisterZrpcServer(grpcServer *grpc.Server, ctx *svc.ServiceContext) {
    
		helloworld.RegisterHelloworldServer(grpcServer, helloworldsvr.NewHelloworld(ctx))
}