// Code generated by jzero. DO NOT EDIT.
// type: simpleapi_client

package simpleapi

import (
	"github.com/jzero-io/restc"
)

type SimpleapiInterface interface {
	RESTClient() restc.Interface

	VersionGetter
}

type SimpleapiClient struct {
	restClient restc.Interface
}

func (x *SimpleapiClient) RESTClient() restc.Interface {
	if x == nil {
		return nil
	}
	return x.restClient
}

func (x *SimpleapiClient) Version() VersionInterface {
	return newVersionClient(x)
}

// NewForConfig creates a new SimpleapiClient for the given config.
func NewForConfig(x *restc.RESTClient) (*SimpleapiClient, error) {
	return &SimpleapiClient{x}, nil
}
