// Code generated by jzero. DO NOT EDIT.
// type: quickstart_client

package quickstart

import (
	"github.com/jzero-io/restc"
)

type QuickstartInterface interface {
	RESTClient() restc.Interface
	
	VersionGetter
	HelloGetter
	
}

type QuickstartClient struct {
	restClient restc.Interface
}

func (x *QuickstartClient) RESTClient() restc.Interface {
	if x == nil {
		return nil
	}
	return x.restClient
}

func (x *QuickstartClient) Version() VersionInterface {
	return newVersionClient(x)
}

func (x *QuickstartClient) Hello() HelloInterface {
	return newHelloClient(x)
}


// NewForConfig creates a new QuickstartClient for the given config.
func NewForConfig(x *restc.RESTClient) (*QuickstartClient, error) {
	return &QuickstartClient{x}, nil
}