// Code generated by jzero. DO NOT EDIT.

package server

import (
	"github.com/zeromicro/go-zero/core/service"
	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
	"google.golang.org/grpc/reflection"

	"simplegateway-with-model-redis/internal/config"
	"simplegateway-with-model-redis/internal/svc"

	usersvr "simplegateway-with-model-redis/internal/server/user"
	versionsvr "simplegateway-with-model-redis/internal/server/version"

	"simplegateway-with-model-redis/internal/types/user"
	"simplegateway-with-model-redis/internal/types/version"
)

// RegisterZrpc Deprecated: use RegisterZrpcServer instead.
func RegisterZrpc(c config.Config, ctx *svc.ServiceContext) *zrpc.RpcServer {
	s := zrpc.MustNewServer(c.Zrpc.RpcServerConf, func(grpcServer *grpc.Server) {
	    
		user.RegisterUserServer(grpcServer, usersvr.NewUser(ctx))
		version.RegisterVersionServer(grpcServer, versionsvr.NewVersion(ctx))

		if c.Zrpc.Mode == service.DevMode || c.Zrpc.Mode == service.TestMode {
			reflection.Register(grpcServer)
		}
	})

	return s
}

func RegisterZrpcServer(grpcServer *grpc.Server, ctx *svc.ServiceContext) {
    
		user.RegisterUserServer(grpcServer, usersvr.NewUser(ctx))
		version.RegisterVersionServer(grpcServer, versionsvr.NewVersion(ctx))
}